import {
  clearProjectMessages,
  createProjectMessage,
  deleteProjectMessage,
  uploadProjectChatFiles
} from '../../services/chat.service.js';

const BUCKET = 'project-chat-files';

export function createChatFeature(deps) {
  const { S, $, opts, esc, dt, uname, byId } = deps;
function ensureChatTools(){let p=document.querySelector('#chat .chat-panel');if(!p)return;if(!$('chatSearch')){let head=p.querySelector('.panel-head'),div=document.createElement('div');div.className='chat-tools';div.innerHTML='<input class="input" id="chatSearch" placeholder="Поиск по чату"><button class="btn secondary" id="clearChatBtn" type="button">Очистить чат</button>';(head||p).insertAdjacentElement('afterend',div);$('chatSearch').addEventListener('input',renderChat);$('clearChatBtn').onclick=()=>clearChat().catch(x=>alert(x.message||x))}ensureChatComposer()}
function ensureChatComposer(){let c=document.querySelector('#chat .chat-compose'),txt=$('chatText'),file=$('chatFiles'),send=$('sendChatBtn');if(!c||!txt||!file||!send||c.classList.contains('wk-compact'))return;c.classList.add('wk-compact');let lab=document.createElement('label');lab.className='chat-file-btn';lab.setAttribute('for','chatFiles');lab.title='Прикрепить файл или изображение';lab.textContent='+';c.insertBefore(lab,txt);send.classList.add('chat-send');c.insertBefore(send,txt.nextSibling);let sum=document.createElement('div');sum.id='chatFileSummary';sum.className='chat-file-summary';sum.textContent='';c.appendChild(sum);file.addEventListener('change',()=>{let n=file.files?.length||0;sum.textContent=n?`Выбрано файлов: ${n}`:''})}
function msgHtml(body){let out=[],lines=String(body||'').split(/\n/);for(let line of lines){let m=line.match(/^(📎|🖼)\s+(.+?):\s+(https?:\/\/\S+)/);if(m){let isImg=m[1]==='🖼',name=esc(m[2]),url=esc(m[3]);out.push(isImg?`<a class="chat-img-link" href="${url}" target="_blank" rel="noopener"><img src="${url}" alt="${name}"><span>${name}</span></a>`:`<a class="chat-file-link" href="${url}" target="_blank" rel="noopener">📎 <span>${name}</span></a>`)}else if(line.trim())out.push(`<div>${esc(line)}</div>`);else out.push('<br>')}return out.join('')}
function renderChat(){ensureChatTools();if(!S.activeChat&&S.projects[0])S.activeChat=S.projects[0].id;let sel=$('chatProject');if(sel){opts('chatProject',S.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join(''));sel.value=S.activeChat||''}let box=$('chatMessages');if(!box)return;let q=($('chatSearch')?.value||'').toLowerCase();let list=S.messages.filter(m=>m.project_id===S.activeChat&&!m.deleted_at&&(!q||[m.body,m.content,uname(m.author_id)].join(' ').toLowerCase().includes(q)));box.innerHTML=list.map(m=>`<div class="chat-bubble ${m.author_id===S.profile?.id?'mine':''}"><button class="chat-x" data-action="delete-chat-message" data-id="${m.id}" title="Удалить сообщение">×</button><div class="chat-meta">${esc(uname(m.author_id))} · ${dt(m.created_at)}</div><div>${msgHtml(m.body||m.content||'')}</div></div>`).join('')||'<div class="empty">Сообщений пока нет</div>';box.scrollTop=box.scrollHeight}
async function uploadChatFiles(project_id){let input=$('chatFiles'),files=[...(input?.files||[])];if(!files.length)return[];return await uploadProjectChatFiles(S.sb,BUCKET,project_id,files)}
async function sendChat(){let project_id=$('chatProject')?.value||S.activeChat,txt=($('chatText')?.value||'').trim();if(!project_id)return;let btn=$('sendChatBtn');if(btn){btn.disabled=true;btn.textContent='...'}try{let files=await uploadChatFiles(project_id),fileLines=files.map(f=>`${f.isImage?'🖼':'📎'} ${f.name}: ${f.url}`);let body=[txt,fileLines.join('\n')].filter(Boolean).join('\n\n');if(!body)return;let row=await createProjectMessage(S.sb,{project_id,body,author_id:S.profile?.id});S.messages.push(row);$('chatText')&&($('chatText').value='');if($('chatFiles'))$('chatFiles').value='';if($('chatFileSummary'))$('chatFileSummary').textContent='';S.activeChat=project_id;renderChat()}finally{if(btn){btn.disabled=false;btn.textContent='Отправить'}}}
async function deleteMessage(id){let m=byId(S.messages,id);if(m)m.deleted_at=new Date().toISOString();renderChat();await deleteProjectMessage(S.sb,id)}
async function clearChat(){let pid=$('chatProject')?.value||S.activeChat;if(!pid)return;if(!confirm('Очистить сообщения выбранного чата?'))return;S.messages.forEach(m=>{if(m.project_id===pid)m.deleted_at=new Date().toISOString()});renderChat();await clearProjectMessages(S.sb,pid)}

  return { ensureChatTools, ensureChatComposer, msgHtml, renderChat, uploadChatFiles, sendChat, deleteMessage, clearChat };
}
