from pathlib import Path
import re
root=Path('.')
r=root/'assets/app-runtime.js'; css=root/'assets/app.css'; idx=root/'index.html'; loader=root/'assets/app.js'; wf=root/'.github/workflows/static.yml'
old=root/'.github/scripts/apply_recurrence_scope.py'; self=root/'.github/scripts/apply_task_links.py'; wfs=root/'.github/workflows/apply-task-links.yml'
ver='20260520-task-links-v1'
if old.exists():
    exec(compile(old.read_text(encoding='utf-8'),str(old),'exec'),{'__name__':'__main__'})
JS=r'''
/* Task links v1 start */
function tlDone(t){return !t||t.status==='done'||!!t.completed_at}function tlTask(id){return byId(S.tasks,id)}
function tlIn(id,a=false){return(S.taskLinks||[]).filter(l=>l.type==='blocks'&&l.target_task_id===id).filter(l=>!a||!tlDone(tlTask(l.source_task_id)))}
function tlOut(id,a=false){return(S.taskLinks||[]).filter(l=>l.type==='blocks'&&l.source_task_id===id).filter(l=>!a||!tlDone(tlTask(l.target_task_id)))}
function tlRel(id){return(S.taskLinks||[]).filter(l=>l.type==='relates_to'&&(l.source_task_id===id||l.target_task_id===id))}
function tlCnt(t){let id=t?.id;return id?{w:tlIn(id,true).length,b:tlOut(id,true).length,r:tlRel(id).length}:{w:0,b:0,r:0}}
function tlBadges(t){let c=tlCnt(t),a=[];if(c.w)a.push('<span class="tlb wait">Ждёт: '+c.w+'</span>');if(c.b)a.push('<span class="tlb block">Блокирует: '+c.b+'</span>');if(c.r)a.push('<span class="tlb rel">Связи: '+c.r+'</span>');return a.length?'<div class="tlbs">'+a.join('')+'</div>':''}
function tlOther(l,id){return l.source_task_id===id?l.target_task_id:l.source_task_id}function tlTitle(t){return t?esc(t.title)+' <small>'+esc(pname(t.project_id))+' · '+(tlDone(t)?'завершено':esc(ST[t.status]||t.status||''))+'</small>':'—'}
function tlRow(l,id){let oid=l.type==='blocks'?(l.source_task_id===id?l.target_task_id:l.source_task_id):tlOther(l,id),t=tlTask(oid);return'<div class="task-link-row '+(tlDone(t)?'done':'')+'"><button type="button" data-action="open-linked-task" data-id="'+(t?.id||'')+'">'+tlTitle(t)+'</button><button type="button" class="x" data-action="delete-task-link" data-id="'+l.id+'">×</button></div>'}
function tlOptions(id){return S.tasks.filter(t=>!t.deleted_at&&t.id!==id).sort((a,b)=>String(a.title||'').localeCompare(String(b.title||''),'ru')).map(t=>'<option value="'+esc(t.title)+' ['+t.id+']">'+esc(pname(t.project_id))+'</option>').join('')}
function ensureTaskLinksUi(){if($('taskLinksBox'))return;let a=$('taskRecurrenceScopeBox')||$('taskRepeatExistingNote')||$('taskNotes')?.closest('label')||$('taskDue')?.closest('label');if(!a)return;let b=document.createElement('div');b.id='taskLinksBox';b.className='full task-links-box';a.parentNode.insertBefore(b,a.nextSibling)}
function renderTaskLinksModal(id){ensureTaskLinksUi();let b=$('taskLinksBox');if(!b)return;if(!id){b.innerHTML='<details><summary>Связи</summary><div class="muted">Сохраните задачу, чтобы добавить связи.</div></details>';return}let i=tlIn(id),o=tlOut(id),r=tlRel(id);b.innerHTML='<details open><summary>Связи '+tlBadges(tlTask(id))+'</summary><div class="task-link-sec"><b>Ждёт выполнения</b>'+(i.length?i.map(l=>tlRow(l,id)).join(''):'<div class="muted">Нет блокирующих задач.</div>')+'</div><div class="task-link-sec"><b>Блокирует</b>'+(o.length?o.map(l=>tlRow(l,id)).join(''):'<div class="muted">Нет зависимых задач.</div>')+'</div><div class="task-link-sec"><b>Связанные задачи</b>'+(r.length?r.map(l=>tlRow(l,id)).join(''):'<div class="muted">Нет связанных задач.</div>')+'</div><div class="task-link-add"><b>Добавить связь</b><input class="input" id="taskLinkSearch" list="taskLinkOptions" placeholder="Начните вводить название задачи"><datalist id="taskLinkOptions">'+tlOptions(id)+'</datalist><select class="input" id="taskLinkType"><option value="blocks">Блокирует</option><option value="relates_to">Связана с</option></select><button type="button" class="btn sm primary" data-action="add-task-link" data-id="'+id+'">Добавить связь</button></div></details>'}
function tlTarget(v){v=String(v||'').trim();let m=v.match(/\[([0-9a-fA-F-]{30,})\]$/);if(m)return m[1];let q=v.toLowerCase();return(S.tasks.find(t=>String(t.title||'').toLowerCase()===q)||S.tasks.find(t=>String(t.title||'').toLowerCase().includes(q)))?.id||null}
function tlExists(s,t,typ){return(S.taskLinks||[]).some(l=>l.type===typ&&((l.source_task_id===s&&l.target_task_id===t)||(typ==='relates_to'&&l.source_task_id===t&&l.target_task_id===s)))}
function tlCycle(s,t){let seen=new Set();function walk(id){if(id===s)return true;if(seen.has(id))return false;seen.add(id);return(S.taskLinks||[]).filter(l=>l.type==='blocks'&&l.source_task_id===id).some(l=>walk(l.target_task_id))}return walk(t)}
async function loadTaskLinks(){S.taskLinks=await optional('task_links',S.sb.from('task_links').select('*').order('created_at',{ascending:true}),6500);return S.taskLinks}
async function createTaskLink(cur,tgt,typ){if(!cur||!tgt)return alert('Выберите связанную задачу');if(cur===tgt)return alert('Задача не может блокировать сама себя');if(tlExists(cur,tgt,typ))return alert('Эта задача уже связана');if(typ==='blocks'&&tlCycle(cur,tgt))return alert('Нельзя создать циклическую блокировку');let r=await S.sb.from('task_links').insert({source_task_id:cur,target_task_id:tgt,type:typ,created_by:S.profile?.id||null}).select().single();if(r.error)return alert(String(r.error.message||'').includes('duplicate')?'Эта задача уже связана':r.error.message);S.taskLinks.push(r.data);renderTaskLinksModal(cur);scheduleRender('task-links')}
async function deleteTaskLink(id){let cur=$('taskId')?.value||null,r=await S.sb.from('task_links').delete().eq('id',id);if(r.error)return alert(r.error.message);S.taskLinks=(S.taskLinks||[]).filter(x=>x.id!==id);renderTaskLinksModal(cur);scheduleRender('task-links')}
function injectTaskLinkFilters(){let root=$('tasks');if(!root||$('taskLinkFilterBar'))return;let bar=document.createElement('div');bar.id='taskLinkFilterBar';bar.className='task-link-filterbar';bar.innerHTML='<button class="btn sm secondary" data-action="task-link-filter" data-filter="all">Все</button><button class="btn sm secondary" data-action="task-link-filter" data-filter="blocked">Заблокированные</button><button class="btn sm secondary" data-action="task-link-filter" data-filter="blocking">Блокирующие другие</button><button class="btn sm secondary" data-action="task-link-filter" data-filter="ready">Можно делать сейчас</button>';root.prepend(bar)}
function cardId(c){return c.dataset.id||c.querySelector('[data-id]')?.dataset.id||c.getAttribute('data-task-id')||''}function tBlocked(t){return tlCnt(t).w>0}function tBlocking(t){return tlCnt(t).b>0}
function annotateTaskCards(){qa('.task-card').forEach(c=>{let t=tlTask(cardId(c));if(!t)return;c.querySelectorAll('.tlbs').forEach(x=>x.remove());let h=c.querySelector('h4')||c.querySelector('.task-title')||c.firstElementChild,html=tlBadges(t);if(html&&h)h.insertAdjacentHTML('afterend',html);c.classList.toggle('task-link-blocked',tBlocked(t))});applyTaskLinkFilter()}
function applyTaskLinkFilter(){let f=S.taskLinkFilter||localStorage.getItem('pt_task_link_filter')||'all';qa('#taskLinkFilterBar [data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));qa('.task-card').forEach(c=>{let t=tlTask(cardId(c)),ok=true;if(t){if(f==='blocked')ok=tBlocked(t);if(f==='blocking')ok=tBlocking(t);if(f==='ready')ok=!tBlocked(t)}c.style.display=ok?'':'none'})}
function tval(t,end){let d=(end?(t?.due_date||t?.start_date):(t?.start_date||t?.due_date))||today(),tm=end?(t?.end_time||t?.start_time||'23:59'):(t?.start_time||'00:00');return new Date(String(d).slice(0,10)+'T'+String(tm).slice(0,5)+':00').getTime()}
function timelineConflict(t){return tlIn(t.id,true).some(l=>tval(tlTask(l.source_task_id),true)>tval(t,false))}function linkedIds(id){let s=new Set();(S.taskLinks||[]).forEach(l=>{if(l.source_task_id===id)s.add(l.target_task_id);if(l.target_task_id===id)s.add(l.source_task_id)});return s}
function annotateTimelineLinks(){qa('.timeline-event[data-id],.wk-tlitem[data-id]').forEach(e=>{let t=tlTask(e.dataset.id);if(!t)return;e.classList.toggle('task-link-conflict',timelineConflict(t));let f=S.taskLinkTimelineFocus,l=f?linkedIds(f):new Set();e.classList.toggle('task-link-focus',f===t.id);e.classList.toggle('task-link-linked',l.has(t.id))})}
(function installTaskLinks(){if(S.taskLinksInstalled)return;S.taskLinksInstalled=1;S.taskLinks=S.taskLinks||[];let bl=load;load=async function(){await bl.apply(this,arguments);await loadTaskLinks();render()};let bo=openTask;openTask=function(id){bo.apply(this,arguments);setTimeout(()=>renderTaskLinksModal(id),0)};let brt=renderTasks;renderTasks=function(){brt.apply(this,arguments);injectTaskLinkFilters();annotateTaskCards()};let brl=renderTimeline;renderTimeline=function(){brl.apply(this,arguments);setTimeout(annotateTimelineLinks,0)};document.addEventListener('click',e=>{let b=e.target.closest?.('[data-action]');if(!b)return;let a=b.dataset.action;if(a==='add-task-link'){e.preventDefault();createTaskLink(b.dataset.id,tlTarget($('taskLinkSearch')?.value),$('taskLinkType')?.value||'blocks')}if(a==='delete-task-link'){e.preventDefault();deleteTaskLink(b.dataset.id)}if(a==='open-linked-task'){e.preventDefault();if(b.dataset.id)openTask(b.dataset.id)}if(a==='task-link-filter'){e.preventDefault();S.taskLinkFilter=b.dataset.filter||'all';localStorage.setItem('pt_task_link_filter',S.taskLinkFilter);applyTaskLinkFilter()}if(a==='tl-open'&&b.dataset.id){S.taskLinkTimelineFocus=b.dataset.id;setTimeout(annotateTimelineLinks,0)}},true)})();
/* Task links v1 end */
'''
CSS=r'''
/* Task links v1 start */
.task-links-box{border:1px solid #e5e7eb;border-radius:14px;background:#fff;padding:10px;margin-top:10px}.task-links-box summary{cursor:pointer;font-weight:800}.task-link-sec{display:grid;gap:6px;margin:10px 0}.task-link-row{display:grid;grid-template-columns:1fr 26px;gap:6px;align-items:center;border:1px solid #eef2f7;border-radius:10px;background:#f8fafc;padding:6px}.task-link-row.done{opacity:.58}.task-link-row button:first-child{border:0;background:transparent;text-align:left;font-weight:700;cursor:pointer}.task-link-row small{display:block;color:#64748b;font-weight:400}.task-link-row .x{border:0;border-radius:8px;background:#fee2e2;color:#991b1b;font-weight:900;cursor:pointer}.task-link-add{display:grid;grid-template-columns:1fr 150px auto;gap:8px;align-items:end;border-top:1px solid #eef2f7;padding-top:10px}.task-link-add b{grid-column:1/-1}.tlbs{display:flex;gap:4px;flex-wrap:wrap;margin:4px 0}.tlb{display:inline-flex;border-radius:999px;border:1px solid #dbe4ef;background:#f8fafc;color:#475569;padding:2px 6px;font-size:11px;font-weight:800}.tlb.wait{background:#fff7ed;color:#9a3412;border-color:#fed7aa}.tlb.block{background:#eff6ff;color:#1d4ed8;border-color:#bfdbfe}.tlb.rel{background:#f5f3ff;color:#6d28d9;border-color:#ddd6fe}.task-link-filterbar{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 10px}.task-link-filterbar .active{background:#0f172a!important;color:#fff!important}.task-card.task-link-blocked{box-shadow:inset 3px 0 0 #f97316}.timeline-event.task-link-conflict,.wk-tlitem.task-link-conflict{outline:2px solid #f97316!important;box-shadow:0 0 0 3px rgba(249,115,22,.16)!important}.timeline-event.task-link-focus,.wk-tlitem.task-link-focus{outline:2px solid #2563eb!important}.timeline-event.task-link-linked,.wk-tlitem.task-link-linked{outline:2px dashed #7c3aed!important}@media(max-width:720px){.task-link-add{grid-template-columns:1fr}.task-link-add b{grid-column:auto}}
/* Task links v1 end */
'''
def insert_main(s,block):
    marker='\n})();\n\n/* Timeline dynamic lane heights'
    p=s.find(marker)
    if p<0:p=s.rfind('\n})();')
    if p<0:raise SystemExit('runtime closure marker not found')
    return s[:p]+block+s[p:]
s=r.read_text(encoding='utf-8')
s=re.sub(r'/\* Task links v1 start \*/[\s\S]*?/\* Task links v1 end \*/\n?','',s)
s=s.replace('taskComments:[],messages:', 'taskComments:[],taskLinks:[],messages:')
s=insert_main(s,JS)
r.write_text(s,encoding='utf-8')
cs=css.read_text(encoding='utf-8') if css.exists() else ''
cs=re.sub(r'/\* Task links v1 start \*/[\s\S]*?/\* Task links v1 end \*/\n?','',cs)
css.write_text(cs.rstrip()+'\n'+CSS,encoding='utf-8')
h=idx.read_text(encoding='utf-8')
h=re.sub(r"assets/app\.js\?v=[^'\"]+",'assets/app.js?v='+ver,h);h=re.sub(r"assets/app\.css\?v=[^'\"]+",'assets/app.css?v='+ver,h);idx.write_text(h,encoding='utf-8')
if loader.exists():
    a=loader.read_text(encoding='utf-8');a=re.sub(r"assets/app-runtime\.js\?v=[^'\"]+",'assets/app-runtime.js?v='+ver,a);loader.write_text(a,encoding='utf-8')
if wf.exists():
    wf.write_text('''name: Deploy static content to Pages\n\non:\n  push:\n    branches: ["main"]\n  workflow_dispatch:\n\npermissions:\n  contents: read\n  pages: write\n  id-token: write\n\nconcurrency:\n  group: "pages"\n  cancel-in-progress: false\n\njobs:\n  deploy:\n    environment:\n      name: github-pages\n      url: ${{ steps.deployment.outputs.page_url }}\n    runs-on: ubuntu-latest\n    steps:\n      - name: Checkout\n        uses: actions/checkout@v4\n      - name: Setup Pages\n        uses: actions/configure-pages@v5\n      - name: Upload artifact\n        uses: actions/upload-pages-artifact@v3\n        with:\n          path: '.'\n      - name: Deploy to GitHub Pages\n        id: deployment\n        uses: actions/deploy-pages@v5\n''',encoding='utf-8')
for p in [old,self,wfs,root/'.github/workflows/apply-recurrence-scope.yml']:
    if p.exists():p.unlink()
