const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const runtime=fs.readFileSync(path.join(root,'assets/app-runtime.js'),'utf8');
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20261002085918_task_acknowledgements.sql'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/task-acknowledgements.css'),'utf8');
const names=['taskAssignmentToken','taskAcknowledgement','taskSeenState','taskSeenLabel','taskSeenButton','taskSeenSummary','acknowledgeTask','syncTaskAssignees'];
const source=names.map(name=>runtime.split(/\r?\n/).find(l=>l.startsWith('function '+name+'(')||l.startsWith('async function '+name+'('))).join('\n');
const task={id:'t1',assignee_id:'member',assignee_revision:'legacy-1',status:'planned'};
const S={profile:{id:'member'},tasks:[task],assignees:[{id:'a1',task_id:'t1',user_id:'member'}],acknowledgements:[]};
let calls=0,resolveRpc;
S.sb={rpc(name,args){calls++;return new Promise(resolve=>resolveRpc=resolve)}};
const live={textContent:''};
const context={S,TASK_ACK_WRITES:new Set(),byId:(arr,id)=>arr.find(x=>x.id===id),tids:t=>[...new Set(S.assignees.filter(a=>a.task_id===t.id).map(a=>a.user_id).concat(t.assignee_id?[t.assignee_id]:[]))],uname:id=>id,esc:String,dt:String,refreshTaskSeenUI(){},withTimeout:p=>p,$:()=>live,rtUpsert:(table,row)=>S.acknowledgements.push(row),Set,Error};
vm.createContext(context);vm.runInContext(source,context);
const {taskSeenState,taskSeenButton,taskAcknowledgement,acknowledgeTask}=context;
assert.equal(taskSeenState(task).seen.length,0);
assert.match(taskSeenButton(task),/Подтвердить ознакомление/);
assert.match(taskSeenButton(task),/aria-pressed="false"/);
S.profile={id:'owner'};
assert.equal(taskSeenState(task).mine,false);

(async()=>{
  await acknowledgeTask('t1');assert.equal(calls,0,'owner cannot acknowledge on behalf of assignee');
  S.profile={id:'member'};
  const pending=acknowledgeTask('t1');
  assert.equal(context.TASK_ACK_WRITES.size,1);
  assert.match(taskSeenButton(task),/disabled aria-busy="true"/);
  await acknowledgeTask('t1');assert.equal(calls,1,'double click sends only one request');
  resolveRpc({data:{id:'receipt',task_id:'t1',user_id:'member',assignment_token:'a1',acknowledged_at:'2026-10-02T10:00:00Z'},error:null});
  await pending;
  assert.equal(taskSeenState(task).all,true);
  assert.equal(task.status,'planned','acknowledgement does not complete or change task status');
  assert.match(taskSeenButton(task),/is-seen/);assert.match(taskSeenButton(task),/aria-pressed="true"/);
  await acknowledgeTask('t1');assert.equal(calls,1,'acknowledgement is one-way and idempotent');
  assert.match(live.textContent,/подтверждено/);
  task.title='Edited';assert.ok(taskAcknowledgement(task,'member'),'normal edits retain acknowledgement');
  S.assignees[0].id='a2';assert.equal(taskAcknowledgement(task,'member'),undefined,'new assignment never reuses old receipt');
  S.assignees=[];
  S.acknowledgements.push({id:'legacy',task_id:'t1',user_id:'member',assignment_token:'legacy-1'});
  assert.ok(taskAcknowledgement(task,'member'),'legacy single assignments are supported');
  task.assignee_revision='legacy-2';assert.equal(taskAcknowledgement(task,'member'),undefined);
  S.assignees=[{id:'a1',task_id:'t1',user_id:'member'},{id:'a3',task_id:'t1',user_id:'member2'}];
  assert.equal(taskSeenState(task).all,false);assert.match(taskSeenButton(task),/is-partial/);assert.match(taskSeenButton(task),/1\/2/);
  S.assignees[0].id='a2';
  const failed=acknowledgeTask('t1');resolveRpc({data:null,error:{message:'Network error'}});
  await assert.rejects(failed);assert.equal(context.TASK_ACK_WRITES.size,0);assert.equal(taskSeenState(task).mineSeen,false,'failure never creates a false confirmation');
  let captured;S.sb.rpc=async(name,args)=>{captured={name,args};return{error:null}};
  await context.syncTaskAssignees('t1',['member','member',null,'member2']);
  assert.equal(captured.name,'sync_task_assignees');assert.equal(captured.args.p_users.join(','),'member,member2');
  assert.match(migration,/enable row level security/);
  assert.match(migration,/user_id = \(select public\.current_app_user_id\(\)\)/);
  assert.match(migration,/u\.auth_user_id = \(select auth\.uid\(\)\)/);
  assert.doesNotMatch(migration,/security definer/i);
  assert.match(migration,/assignment_id uuid references public\.task_assignees\(id\) on delete cascade/);
  assert.match(migration,/grant insert \(task_id, user_id, assignment_id, assignment_token\)/);
  assert.doesNotMatch(migration,/grant (all|update|delete)/i);
  assert.match(migration,/on conflict \(task_id,user_id,assignment_token\) do nothing/);
  assert.match(migration,/alter publication supabase_realtime add table public\.task_acknowledgements/);
  assert.match(runtime,/if\(table==='task_acknowledgements'\)refreshTaskSeenUI\(row.task_id\)/,'receipt events patch controls without rerendering the task card');
  assert.match(runtime,/'task_assignees','task_acknowledgements','task_subtasks'/);
  assert.match(runtime,/task-card-topline\">\$\{taskSeenButton\(t\)\}/);
  assert.doesNotMatch(runtime.split(/\r?\n/).find(l=>l.startsWith('async function saveTask(')),/task_assignees'\)\.delete/);
  assert.match(css,/min-width:44px;height:44px/);
  assert.match(css,/transition:none!important/);
  console.log('task acknowledgements: permissions, double-click, errors, multiple/legacy assignments, edits and realtime checks passed');
})().catch(e=>{console.error(e);process.exitCode=1});
