const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname,'..');
const source = fs.readFileSync(path.join(root,'assets/task-inspector.js'),'utf8');
const css = fs.readFileSync(path.join(root,'assets/task-inspector.css'),'utf8');
const runtime = fs.readFileSync(path.join(root,'assets/app-runtime.js'),'utf8');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');

assert.match(html,/assets\/task-inspector\.css\?v=20261002-inspector-v1/);
assert.match(html,/assets\/task-inspector\.js\?v=20261002-inspector-v1/);
assert.ok(html.indexOf("src='assets/task-inspector.js") < html.indexOf("src='assets/app.js"),'inspector installs before the task runtime');
assert.match(source,/mq\.matches \? dialog\.show\(\) : dialog\.showModal\(\)/,'desktop is modeless, mobile is an accessible full-screen dialog');
assert.match(source,/closest\('\.task-inspector-tabs > \[data-inspector-tab\]'\)/);
assert.doesNotMatch(source,/closest\('\[data-inspector-tab\]'\)/,'do not mistake the inspector container for a tab and swallow all clicks');
assert.match(source,/form\.addEventListener\('invalid',\(\) => chooseTab\('details'\),true\)/);
assert.match(source,/form\.addEventListener\('submit',protectCommentDraft,true\)/);
assert.match(css,/grid-template-columns:minmax\(0,1fr\)!important/);
assert.match(css,/backdrop-filter:none!important/);
assert.match(css,/task-inspector-open:not\(\.task-inspector-expanded\) \.main\{margin-right:var\(--task-inspector-width\)\}/);
assert.match(css,/\.form-grid\[hidden\]/);
assert.match(runtime,/decision===false\)return false/);
assert.match(runtime,/decision==='reuse'/);
assert.match(runtime,/comment_subtask_id:s\.id,tab:'comments'/);
assert.match(runtime,/preset:\{start_date:d,due_date:d\}/,'date defaults are passed atomically after any discard confirmation');
const weekHandler = runtime.slice(runtime.indexOf('/* Week add task integrated start */'),runtime.indexOf('/* Week add task integrated end */'));
assert.doesNotMatch(weekHandler,/pointerdown|setTimeout/,'one click opens one editor; no delayed writes into another task');

function extract(name){
  const start = source.indexOf('  function '+name+'(');
  assert.ok(start >= 0,name);
  const next = source.indexOf('\n  function ',start+1);
  return source.slice(start,next);
}
const nodes = new Map();
for(const id of ['taskId','taskTitle','taskProject','taskAssignee','taskStatus','taskPriority','taskStart','taskDue','taskNotes','taskAllDay','taskStartTime','taskEndTime','taskDurationMinutes','taskRepeatEnabled','taskRepeatType','taskRepeatUntil','taskCommentText']){
  nodes.set(id,{value:'',checked:false,type:'text'});
}
nodes.get('taskAssignee').multiple = true;
nodes.get('taskAssignee').selectedOptions = [{value:'a'},{value:'b'}];
nodes.get('taskAllDay').type = 'checkbox';
nodes.get('taskRepeatEnabled').type = 'checkbox';
nodes.set('taskSaveBtn',{disabled:false,getAttribute(){return null}});
nodes.set('taskInspectorDiscard',{hidden:true});
nodes.set('taskInspectorKeep',{focus(){}});
let editor = null;
const form = {querySelectorAll(){return []},querySelector(selector){return selector === '.task-comment-edit-text' ? editor : null}};
const dialog = {open:true};
const context = vm.createContext({dialog,form,$:id=>nodes.get(id),JSON,Array,Boolean});
vm.runInContext("let baseline='',pendingAction=null,allowNextOpen=false; const fieldIds="+JSON.stringify([...nodes.keys()].filter(id=>!['taskId','taskCommentText','taskSaveBtn','taskInspectorDiscard','taskInspectorKeep'].includes(id)))+';\n'+['snapshot','dirty','saving','guard','prepareOpen'].map(extract).join('\n'),context);
vm.runInContext('baseline=snapshot()',context);
let resumes = 0;
context.resume = () => resumes++;
assert.equal(vm.runInContext("prepareOpen('other',null,{},resume)",context),true);
assert.equal(resumes,0,'a clean switch continues exactly once, never re-enters the runtime');
nodes.get('taskTitle').value = 'Несохранённая задача';
assert.equal(vm.runInContext("prepareOpen('other',null,{},resume)",context),false);
assert.equal(nodes.get('taskInspectorDiscard').hidden,false);
assert.equal(resumes,0,'dirty switch waits for the user');
vm.runInContext('pendingAction()',context);
assert.equal(resumes,1,'discard resumes the intended switch once');
assert.equal(vm.runInContext("prepareOpen('other',null,{},resume)",context),true,'discard bypass is one-shot');
assert.equal(vm.runInContext("prepareOpen('other',null,{},resume)",context),false,'later switches are protected again');
nodes.get('taskId').value = 'same';
assert.equal(vm.runInContext("prepareOpen('same',null,{tab:'comments'},resume)",context),'reuse','same-task comments preserve the unsaved form');
nodes.get('taskId').value = '';
nodes.get('taskTitle').value = '';
assert.equal(vm.runInContext('dirty()',context),false);
nodes.get('taskCommentText').value = 'Комментарий';
assert.equal(vm.runInContext('dirty()',context),true,'an unsent comment is protected');
nodes.get('taskCommentText').value = '';
editor = {value:'Редактируемый комментарий'};
assert.equal(vm.runInContext('dirty()',context),true,'comment editing is protected');
editor = null;
nodes.get('taskSaveBtn').disabled = true;
assert.equal(vm.runInContext("prepareOpen('other',null,{},resume)",context),false,'cannot change task while its save is pending');
dialog.open = false;
assert.equal(vm.runInContext('dirty()',context),false);
console.log('Modeless task inspector, tab routing and unsaved-draft checks passed');
